### ISSUE TITLE
required:true missing for PUT and DELETE

### ISSUE THREAD

**Issue by cwienands** [Dropsource/serverless-todo-api-example#1]
The `id` parameter in `GET todos/{id}` has `required: true` set. That setting is missing from the PUT and DELETE operations. As a result, the generates Swagger spec causes errors like this one:

`Semantic error at paths./todos/{id}.put.parameters.0
Path parameters must have 'required: true'. You can always create another path/operation without this parameter to get the same behaviour.`

**Comment by dperjar** [comment]
Thank you, Cristoph! I've added the required property to those two operations.
